[Service]
# name of process, required
Name = "exampled"
# optional, humanreadable description, basically a comment.
Description = "This file is example of Service configuration"
# way in which service is marked as ready
# simple - means that process is ready immediately after being spawned
# notify - means that service.notify() has to be called for it to be marked as ready
Type = "simple"

[Exec]
# required if you actually want to run something, path towards lua file to be executed.
Path = "/System/Core/exampled/init.lua"
# optional, default: []
Arguments = ["-m", "Hello World!"]
# optional, default: "/"
WorkingDir = "/"

[Limits]
# define your limits here, similar to proc.limit, by default - default limits apply
MaxPorts = 1024
MaxThreads = 1024
MaxProcesses = 1024
MaxFiles = 16

[User]
# user to run as, requires file to be owned by root, by default - owner of file
User = 0
# group to run as, requires file to be owned by root, by default - owner of file
Group = 0

[Environment]
# you can pass environment variables by key table
APIKEY = "REALLY COOL APIKEY TO TRIGGER GITHUB, YAY"

[Restart]
# "no" for no restarts, "on-failure" for restarts if exit code ~= 0, "always" - always restart. Optional, default: "no"
Policy = "no"
# in seconds (optional, default 0)
Delay = 5

[Activation]
# this enables socket activation, optional, default false
Enabled = true
# this defines mount point for socket activation
MountPoint = "/Devices/example"

# it always creates port at 4, which is responsible for service related messages,
# this is same port that is discovered when service is querried.
# for mount point, it creates port at 5.

# socket activation means that your service will not be started on boot, but instead when someone requests it
# i am not sure if this even matters in CC to be fair, where load times are supposed to be miniscule,
# and this is optimisation measure to reduce load times
# but I think I can still implement it "for education purposes",
# as this is great project so far for learning how OSes work

[Dependencies]
# hard dependency, if requirement dies - it is killed,
# if requirement is not there - wont be started
# they can be started up concurrently with their dependencies
# optional, default: []
Requires = []
# soft dependency, wants to be started with another service,
# but it will not be killed and can run without it
# optional, default: []
Wants = []
# requires to be started after dependency have fully loaded
# and marked itself as ready
# optional, default: []
After = []
# requires to be launched before another service, inverse After
# optional, default: []
Before = []
